version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    
    
  pre_build:
    commands:
      - docker build -t helloworld .
  build:
    commands:
      - docker images
      - docker run helloworld echo "Hello, World!"
